services:
  site:
    image: vcp.ocir.io/ax6skxff4k6c/site-staliszeduardo.com.br:${IMAGE_TAG}
    container_name: site-staliszeduardo
    restart: unless-stopped

    ports:
      - "0.0.0.0:8080:80"

    networks:
      - site_frontend

    cpus: "0.50"
    mem_limit: 128m
    mem_reservation: 32m

    security_opt:
      - no-new-privileges:true

networks:
  site_frontend:
    external: true
    name: site-staliszeduardo-net