name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar arquivos
        run: |
          pwd
          ls -la

      - name: Checkout do código
        uses: actions/checkout@v4
        with:
        github-server-url: https://gitlita.staliszeduardo.com.br

      - name: Instalar Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Validar Docker
        run: |
          docker version

      - name: Build da imagem
        run: |
          docker build \
            -t site-staliszeduardo:${{ gitea.sha }} \
            .

      - name: Validar imagem criada
        run: |
          docker image inspect \
            site-staliszeduardo:${{ gitea.sha }}

      - name: Exibir imagens
        run: |
          docker images site-staliszeduardo